version: '2'

networks:
  byfn:

services:
  blockchain-rest-server:
    container_name: blockchain-rest-server
    image: blockchain-rest-server:1.4.3
    restart: always
    networks:
      - byfn
    ports:
      - 3414:3414
    volumes:
      - ./sample-network/docker-compose:/var/
      - ./config:/blockchain-quick-start/config

